#! /bin/bash

# get the search name from the command line
SEARCH=${1}

# get the configuration file from the command line
INSTALLED_CONFIG_FILES=${2}

# get midnight from yesterday in form of MM/DD/YYYY
YESTERDAY=`date -u --date="yesterday" +"%x"`

# convert midnight to GPS time and analyze a day of data
GPS_START_TIME=`lalapps_tconvert ${YESTERDAY}`
GPS_END_TIME=$((${GPS_START_TIME} + 86400))

# month subdir name in form of YYYYMM
MONTH=`lalapps_tconvert -f "%Y%m" ${GPS_START_TIME}`

# day subdir name in form of YYYYMMDD
DAY=`lalapps_tconvert -f "%Y%m%d" ${GPS_START_TIME}`

# name of workflow
WORKFLOW_NAME=sngl_${SEARCH}_${DAY}

# dir to copy output
HTMLDIR=/home/${USER}/public_html/daily_cbc_offline/${SEARCH}/${MONTH}/${DAY}

# mkdir a dir for the month in the format YYYYMM
mkdir -p /home/${USER}/sngl_er6/${SEARCH}/${MONTH}/${DAY}
cd /home/${USER}/sngl_er6/${SEARCH}/${MONTH}/${DAY}

# generate the workflow
pycbc_make_sngl_workflow --name ${WORKFLOW_NAME} \
                         --installed-config-files ${INSTALLED_CONFIG_FILES} \
                         --config-overrides workflow:start-time:${GPS_START_TIME} \
                                            workflow:end-time:${GPS_END_TIME} \
                                            workflow:workflow-html-basedir:${HTMLDIR} \
                                            html:analysis-subtitle:${MONTH}/${DAY} > ${WORKFLOW_NAME}.out 2>&1

# generate workflow
pycbc_basic_pegasus_plan ${WORKFLOW_NAME}.dax /usr1/${USER}/sngl/${SEARCH} >> ${WORKFLOW_NAME}.out 2>&1
